webhook_url = ""
discord_id = ""
username = "Spectro"
send_match_summary = false
include_screenshot = false
ping_when_stuck = false
ping_when_target_is_reached = false
ping_every_x_match = 0
ping_every_x_minutes = 0
discord_control_enabled = false
discord_bot_token = ""
discord_control_user_id = ""
discord_control_channel_id = ""
discord_control_guild_id = ""
